version: '3.4'

services:

  portal-ingress:
    image: nginx:1.23
    volumes:
    - ./ingress-nginx-vhost.conf:/etc/nginx/conf.d/default.conf:ro
    - ./ingress-nginx.conf:/etc/nginx/nginx.conf:ro    
    - ./ssl:/etc/nginx/ssl:ro
    ports:
    - ${ACROWEB3_NETWORK_EXPOSED_PORT}:80
    - ${ACROWEB3_NETWORK_DDS_EXPOSED_PORT_SSL}:443
    depends_on:
      - dds
